DATA:
  DATASET: 'voc'
  TRAIN_JSON: Pascal_VOC/train_.json
  VAL_JSON: Pascal_VOC/val_.json
  CLASSES: 21

TRAIN:
  CROP_SIZE: (512, 512)
  PROB: 0.5
  RATIO: (1, 2)
  ROTATE: (-10, 10)
  BATCH_SIZE: 8
  WARM_UP_EPOCH: 0
  SKIP_VAL: False
  SAVE_EPOCH_INTERVAL: 5
  VAL_EPOCH_INTERVAL: 5

VAL:
  BATCH_SIZE: 16
TEST:
  MODE: 'image'
  IMAGE_PATH: "../data/Pascal_VOC/VOC2007/JPEGImages/"
  VIDEO_PATH: ""
  IS_MERGE: False

MODEL:
  PHASE: 'test'
  NAME: 'fcn32s'
  BACKBONE_NAME: 'vgg19_bn'
  BACKBONE_PRETRAINED: False
  BACKBONE_WEIGHT: "pretrained/vgg19_bn-c79401a0.pth"
  RESUME: False
  FINETUNE: False
  MODEL_WEIGHT: "ckpts/voc/fcn32s_vgg19_bn/fcn32s_vgg19_bn_voc_best_model.pth"

SOLVER:
  LR_POLICY: 'poly'
  LR: 0.0004
  WARM_UP_LR: 0.00004
  STEPS: [30, 60, 90]

GPU_USE: True
GPU_ID: u'0'
CKPT: '../ckpts/voc/fcn32s_vgg19_bn'