DATA:
  DATASET: 'voc'
  TRAIN_JSON: Pascal_VOC/train_.json
  VAL_JSON: Pascal_VOC/val.json
  CLASSES: 21

TRAIN:
  CROP_SIZE: (512, 512)
  PROB: 0.5
  RATIO: (1, 2)
  ROTATE: (-10, 10)
  BATCH_SIZE: 8
  WARM_UP_EPOCH: 0
  SAVE_EPOCH_INTERVAL: 1
  VAL_EPOCH_INTERVAL: 1

TEST:
  MODE: 'image'
  IMAGE_PATH: "../data/Pascal_VOC/VOC2007/JPEGImages/"
  VIDEO_PATH: ""

MODEL:
  PHASE: 'train'
  NAME: 'psp'
  BACKBONE_NAME: 'resnet18'
  BACKBONE_PRETRAINED: True
  BACKBONE_WEIGHT: "pretrained/"
  RESUME: False
  FINETUNE: False
  MODEL_WEIGHT: "ckpts/voc/voc_psp/psp_resnet18_voc_model.pth"
  OUTPUT_STRIDE: 8
  USE_AUX: False

SOLVER:
  LR_POLICY: 'poly'
  LR: 0.0004
  WARM_UP_LR: 0.00004
  STEPS: [30, 60, 90]

PPM:
  POOL_SCALES: (1, 2, 3, 6)

GPU_USE: True
GPU_ID: u'0'
CKPT: '../ckpts/voc/psp_resnet18'