DATA:
  TRAIN_JSON: ADEChallengeData2016/train.json
  VAL_JSON: ADEChallengeData2016/val_.json
  CLASSES: 151

TRAIN:
  BATCH_SIZE: 8
  SAVE_EPOCH: 5

TEST:
  MODE: 'image'
  IMAGE_PATH: "../data/ADEChallengeData2016/images/validation/"
  VIDEO_PATH: ""

MODEL:
  PHASE: 'test'
  NAME: 'psp'
  BACKBONE_NAME: 'mobilenet_v2'
  BACKBONE_PRETRAINED: False
  BACKBONE_WEIGHT: "pretrained/"
  NORM_LAYER: 'bn'
  RESUME: False
  FINETUNE: False
  MODEL_WEIGHT: "ckpts/ade20k/ade20k_psp/psp_mobilenet_v2_ade20k_Epoch_5_model.pth"
  OUTPUT_STRIDE: 8

SOLVER:
  SCHEDULER_NAME: 'step'

PPM:
  POOL_SCALES: (1, 2, 3, 6)

GPU_USE: True
GPU_ID: u'0'
CKPT: '../ckpts/ade20k/ade20k_psp'
