DATA:
  TRAIN_JSON: ADEChallengeData2016/train.json
  VAL_JSON: ADEChallengeData2016/val.json
  CLASSES: 21

MODEL:
  NAME: 'psp'
  BACKBONE_NAME: 'mobilenet_v3_small'
  BACKBONE_PRETRAINED: True
  BACKBONE_WEIGHT: "pretrained/"
  NORM_LAYER: 'bn'
  PHASE: 'train'
  RESUME: False
  FINETUNE: False
  PRETRAINED: True
  MODEL_WEIGHT: "ckpts/ade20k/model.pth"
  ZOOM_FACTOR: 1
  OUTPUT_STRIDE: 8

PPM:
  POOL_SCALES: (1, 2, 3, 6)
  USE_AUX: False

GPU_USE: True
GPU_IDS: u'0,1'
