DATA:
  TRAIN_JSON: ADEChallengeData2016/train.json
  VAL_JSON: ADEChallengeData2016/val.json
  CLASSES: 151

TRAIN:
  BATCH_SIZE: 2

MODEL:
  PHASE: 'train'
  NAME: 'bisenet'
  BACKBONE_NAME: 'shufflenet_v2_x2_0'
  BACKBONE_PRETRAINED: True
  BACKBONE_WEIGHT: "pretrained/"
  NORM_LAYER: 'bn'
  RESUME: False
  FINETUNE: False
  MODEL_WEIGHT: "ckpts/ade20k/model.pth"
  OUTPUT_STRIDE: 32

GPU_USE: True
GPU_IDS: u'0,1'
