DATA:
  TRAIN_JSON: ADEChallengeData2016/train.json
  VAL_JSON: ADEChallengeData2016/val.json
  CLASSES: 21

MODEL:
  NAME: 'denseaspp'
  BACKBONE_NAME: 'densenet121'
  BACKBONE_PRETRAINED: True
  BACKBONE_WEIGHT: "pretrained/"
  NORM_LAYER: 'bn'
  PHASE: 'train'
  RESUME: False
  FINETUNE: False
  PRETRAINED: True
  MODEL_WEIGHT: "ckpts/ade20k/model.pth"
  OUTPUT_STRIDE: 8
  ZOOM_FACTOR: 1


DENSEASPP:
  OUTPUT_STRIDE: 8
  INTER_CHANNELS: 256
  OUT_CHANNELS: 64
  ATROUS_RATE: [3, 6, 12, 18, 24]
  DROP_RATE: 0.1
  USE_AUX: True

GPU_USE: True
GPU_IDS: u'0,1'
