DATA:
  TRAIN_JSON: ADEChallengeData2016/train.json
  VAL_JSON: ADEChallengeData2016/val.json
  CLASSES: 151

TRAIN:
  BATCH_SIZE: 2
MODEL:
  NAME: 'deeplabv3plus'
  BACKBONE_NAME: 'resnet152'
  BACKBONE_PRETRAINED: True
  BACKBONE_WEIGHT: "pretrained/"
  NORM_LAYER: 'bn'
  PHASE: 'train'
  RESUME: False
  FINETUNE: False
  PRETRAINED: True
  MODEL_WEIGHT: "ckpts/ade20k/model.pth"
  OUTPUT_STRIDE: 16 # only 16 for deeplabv3plus

DEEPLABV3PLUS:
  DROPOUT: 0.1

GPU_USE: True
GPU_IDS: u'0,1'
