DATA:
  TRAIN_JSON: ADEChallengeData2016/train.json
  VAL_JSON: ADEChallengeData2016/val.json
  CLASSES: 151

TRAIN:
  BATCH_SIZE: 2
MODEL:
  PHASE: 'train'
  NAME: 'deeplabv3'
  BACKBONE_NAME: 'densenet201'
  BACKBONE_PRETRAINED: True
  BACKBONE_WEIGHT: "pretrained/"
  NORM_LAYER: 'bn'
  RESUME: False
  FINETUNE: False
  MODEL_WEIGHT: "ckpts/ade20k/model.pth"
  OUTPUT_STRIDE: 8

ASPP:
  OUT_CHANNELS: 512
  DROPOUT: 0.1

GPU_USE: True
GPU_IDS: u'0,1'
