DATA:
  TRAIN_JSON: ADEChallengeData2016/train.json
  VAL_JSON: ADEChallengeData2016/val.json
  CLASSES: 151
TRAIN:
  BATCH_SIZE: 16
  MAX_EPOCH: 50
MODEL:
  NAME: 'contextnet' # no backbone
  BACKBONE_NAME: None
  NORM_LAYER: 'bn'
  PHASE: 'train'
  RESUME: False
  FINETUNE: False
  PRETRAINED: True
  MODEL_WEIGHT: "ckpts/ade20k/model.pth"
  OUTPUT_STRIDE: 8

GPU_USE: True
GPU_IDS: u'0,1'
