DATA:
  TRAIN_JSON: ADEChallengeData2016/train.json
  VAL_JSON: ADEChallengeData2016/val.json
  CLASSES: 21

MODEL:
  NAME: 'contextnet' # no backbone
  BACKBONE_NAME: None
  NORM_LAYER: 'bn'
  PHASE: 'train'
  RESUME: False
  FINETUNE: False
  PRETRAINED: True
  MODEL_WEIGHT: "ckpts/ade20k/model.pth"
  OUTPUT_STRIDE: 32

ContextNet:
  USE_AUX: True

GPU_USE: True
GPU_IDS: u'0,1'
