DATA:
  TRAIN_JSON: ADEChallengeData2016/train.json
  VAL_JSON: ADEChallengeData2016/val.json
  CLASSES: 21

MODEL:
  NAME: 'deeplabv3'
  BACKBONE_NAME: 'shufflenet_v2_x0_5'
  BACKBONE_PRETRAINED: True
  BACKBONE_WEIGHT: "pretrained/"
  NORM_LAYER: 'bn'
  PHASE: 'train'
  RESUME: False
  FINETUNE: False
  PRETRAINED: True
  MODEL_WEIGHT: "ckpts/ade20k/model.pth"


ASPP:
  OUTPUT_STRIDE: 8
  OUT_CHANNELS: 512
  DROPOUT: 0.1
  USE_AUX: True

GPU_USE: True
GPU_IDS: u'0,1'
