DATA:
  TRAIN_JSON: ADEChallengeData2016/train.json
  VAL_JSON: ADEChallengeData2016/val.json
  CLASSES: 151

TRAIN:
  BATCH_SIZE: 2

MODEL:
  PHASE: 'train'
  NAME: 'denseaspp'
  BACKBONE_NAME: 'densenet201'
  BACKBONE_PRETRAINED: True
  BACKBONE_WEIGHT: "pretrained/"
  RESUME: False
  FINETUNE: False
  MODEL_WEIGHT: "ckpts/ade20k/model.pth"
  OUTPUT_STRIDE: 8
  ZOOM_FACTOR: 1


DENSEASPP:
  INTER_CHANNELS: 256
  OUT_CHANNELS: 64
  ATROUS_RATE: [3, 6, 12, 18, 24]
  DROP_RATE: 0.1

GPU_USE: True
GPU_ID: u'0'
