DATA:
  TRAIN_JSON: ADEChallengeData2016/train.json
  VAL_JSON: ADEChallengeData2016/val.json
  CLASSES: 151

TRAIN:
  BATCH_SIZE: 2
  SAVE_EPOCH: 10

TEST:
  MODE: 'video'
  IMAGE_PATH: "../data/test/"
  VIDEO_PATH: ""

MODEL:
  PHASE: 'train'
  NAME: 'psp'
  BACKBONE_NAME: 'shufflenet_v2_x0_5'
  BACKBONE_PRETRAINED: True
  BACKBONE_WEIGHT: "pretrained/"
  NORM_LAYER: 'bn'
  RESUME: False
  FINETUNE: False
  MODEL_WEIGHT: ""
  OUTPUT_STRIDE: 8

PPM:
  POOL_SCALES: (1, 2, 3, 6)

GPU_USE: True
GPU_ID: u'0'
