DATA:
  TRAIN_JSON: ADEChallengeData2016/train.json
  VAL_JSON: ADEChallengeData2016/val.json
  CLASSES: 21

MODEL:
  NAME: 'fcn32s'
  BACKBONE_NAME: 'vgg11'
  BACKBONE_PRETRAINED: True
  BACKBONE_WEIGHT: "pretrained/"
  PHASE: 'train'
  RESUME: False
  FINETUNE: False
  PRETRAINED: True
  MODEL_WEIGHT: "ckpts/ade20k/model.pth"


FCN:
  DROP_OUT: 0.1

GPU_USE: True
GPU_ID: u'0'
