DATA:
  TRAIN_JSON: ADEChallengeData2016/train.json
  VAL_JSON: ADEChallengeData2016/val.json
  CLASSES: 151

TRAIN:
  BATCH_SIZE: 4

TEST:
  MODE: 'video'
  IMAGE_PATH: "../data/test/"
  VIDEO_PATH: "/Users/chenhongming/Downloads/1630030519385084.mp4"

MODEL:
  PHASE: 'test'
  NAME: 'psp'
  BACKBONE_NAME: 'shufflenet_v2_x0_5'
  BACKBONE_PRETRAINED: False
  BACKBONE_WEIGHT: "pretrained/"
  NORM_LAYER: 'bn'
  RESUME: False
  FINETUNE: False
  MODEL_WEIGHT: "ckpts/ade20k/ade20k_psp/psp_shufflenet_v2_x0_5_ade20k_Eopoch_2_model.pth"
  OUTPUT_STRIDE: 8

PPM:
  POOL_SCALES: (1, 2, 3, 6)

GPU_USE: True
GPU_IDS: u'0,1'
