DATA:
  TRAIN_JSON: ADEChallengeData2016/train.json
  VAL_JSON: ADEChallengeData2016/val.json
  CLASSES: 21

MODEL:
  NAME: 'deeplabv3plus'
  BACKBONE_NAME: 'resnet18'
  BACKBONE_PRETRAINED: True
  BACKBONE_WEIGHT: "pretrained/"
  NORM_LAYER: 'bn'
  PHASE: 'train'
  RESUME: False
  FINETUNE: False
  PRETRAINED: True
  MODEL_WEIGHT: "ckpts/ade20k/model.pth"


DEEPLABV3PLUS:
  OUTPUT_STRIDE: 16
  DROPOUT: 0.1
  USE_AUX: True

GPU_USE: True
GPU_IDS: u'0,1'
